# Generated by Django 3.0.5 on 2024-03-28 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lesion', models.CharField(max_length=50)),
                ('organe', models.CharField(max_length=50)),
                ('observation', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Lesion',
            },
        ),
        migrations.CreateModel(
            name='Ouverture_yeux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Ouverture_yeux',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=150)),
                ('sexe', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=50)),
                ('pays_origine', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecin', models.CharField(max_length=100)),
                ('paramedical', models.CharField(max_length=100)),
                ('ambulancier', models.CharField(max_length=100)),
                ('origine_appel', models.CharField(max_length=100)),
                ('motif_appel', models.CharField(max_length=255)),
                ('lieux_intervention', models.CharField(max_length=100)),
                ('decision', models.CharField(max_length=100)),
                ('trajet', models.CharField(max_length=100)),
                ('diagnostique_evoque', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'Intervention',
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ht', models.CharField(max_length=10)),
                ('d_bae', models.CharField(max_length=10)),
                ('a_lieu', models.CharField(max_length=10)),
                ('d_lieu', models.CharField(max_length=10)),
                ('asr', models.CharField(max_length=10)),
                ('a_base', models.CharField(max_length=10)),
                ('dsr', models.CharField(max_length=10)),
                ('duree', models.CharField(max_length=15)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'Horaire',
            },
        ),
    ]
