# Generated by Django 3.0.5 on 2024-03-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
