# Generated by Django 3.0.5 on 2024-03-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0002_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
