# Generated by Django 5.0.6 on 2024-05-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0002_consommable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('specialite', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('service', models.CharField(max_length=100)),
                ('annee_recrutement', models.CharField(max_length=10)),
                ('diplome_obtenu', models.CharField(max_length=150)),
                ('grade', models.CharField(max_length=50, null=True)),
                ('commentaire', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'Personnel',
            },
        ),
    ]
