# Generated by Django 3.0.5 on 2024-04-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0003_patient_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ambulancier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='decision',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnostique_evoque',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lieu_intervention',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='motif_appel',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='numero_ambulance',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='trajet',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
