# Generated by Django 5.0.6 on 2024-05-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0003_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='perso_valid',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
