# Generated by Django 5.0.6 on 2024-05-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0004_personnel_perso_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='statut',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
