# Generated by Django 3.0.5 on 2024-04-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0004_auto_20240406_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='origine_appel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
