# Generated by Django 3.0.5 on 2024-04-14 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0005_patient_origine_appel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesion',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient'),
        ),
        migrations.AddField(
            model_name='ouverture_yeux',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient'),
        ),
        migrations.CreateModel(
            name='Reponse_verbale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'Reponse_verbale',
            },
        ),
        migrations.CreateModel(
            name='Reponse_motrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'Reponse_motrice',
            },
        ),
        migrations.CreateModel(
            name='lesions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=50)),
                ('partie_lesion', models.CharField(max_length=25)),
                ('detail_lesion', models.CharField(max_length=50)),
                ('autre', models.CharField(max_length=150)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'Lesions',
            },
        ),
        migrations.CreateModel(
            name='Horaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ht', models.CharField(max_length=15)),
                ('d_base', models.CharField(max_length=15)),
                ('a_lieu', models.CharField(max_length=15)),
                ('d_lieu', models.CharField(max_length=15)),
                ('asr', models.CharField(max_length=15)),
                ('dsr', models.CharField(max_length=15)),
                ('a_base', models.CharField(max_length=15)),
                ('duree', models.CharField(max_length=25)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'Horaires',
            },
        ),
        migrations.CreateModel(
            name='autre_signe_de_vie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fourmillement_extremite', models.CharField(max_length=5)),
                ('mouvement_de_ms', models.CharField(max_length=5)),
                ('mouvement_de_mi', models.CharField(max_length=5)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'autre_signe_vie',
            },
        ),
    ]
