# Generated by Django 3.0.5 on 2024-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0006_auto_20240414_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesions',
            name='detail_lesion',
        ),
        migrations.AddField(
            model_name='lesions',
            name='abdomen',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesions',
            name='bassin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesions',
            name='cou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesions',
            name='crane',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesions',
            name='face',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesions',
            name='mid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesions',
            name='mig',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesions',
            name='msd',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesions',
            name='msg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesions',
            name='rachis',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesions',
            name='thorax',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lesions',
            name='denomination',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lesions',
            name='partie_lesion',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
