# Generated by Django 3.0.5 on 2024-04-19 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0007_auto_20240416_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reponses_verbale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=25)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'reponse_verbale',
            },
        ),
        migrations.CreateModel(
            name='Reponses_motrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=25)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'reponse_motrice',
            },
        ),
        migrations.CreateModel(
            name='Ouverture_des_yeux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=25)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'ouverture_yeux',
            },
        ),
        migrations.CreateModel(
            name='Autres_signe_vie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=25)),
                ('reponse', models.CharField(max_length=5)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'autres_signe_vie',
            },
        ),
    ]
