# Generated by Django 3.0.5 on 2024-04-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0008_autres_signe_vie_ouverture_des_yeux_reponses_motrice_reponses_verbale'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ouverture_des_yeux',
            table='ouverture_des_yeux',
        ),
        migrations.AlterModelTable(
            name='reponses_motrice',
            table='reponses_motrice',
        ),
        migrations.AlterModelTable(
            name='reponses_verbale',
            table='reponses_verbale',
        ),
    ]
