# Generated by Django 3.0.5 on 2024-04-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0009_auto_20240420_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouverture_des_yeux',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
