# Generated by Django 3.0.5 on 2024-04-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0010_ouverture_des_yeux_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponses_motrice',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
