# Generated by Django 3.0.5 on 2024-04-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0011_reponses_motrice_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponses_verbale',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
