# Generated by Django 3.0.5 on 2024-04-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0012_reponses_verbale_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voies_aeriennes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o2', models.CharField(max_length=15)),
                ('intubation', models.CharField(max_length=15)),
                ('sonde', models.CharField(max_length=15)),
                ('fio2', models.CharField(max_length=15)),
                ('frequence', models.CharField(max_length=15)),
                ('vol_courant', models.CharField(max_length=15)),
                ('peep', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'voies_aeriennes',
            },
        ),
        migrations.CreateModel(
            name='Solutes_drogues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'solutes_drogues',
            },
        ),
        migrations.CreateModel(
            name='Mise_en_condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=5, null=True)),
                ('dyn', models.CharField(max_length=5, null=True)),
                ('oxy', models.CharField(max_length=5, null=True)),
                ('coquille', models.CharField(max_length=5, null=True)),
                ('barquette', models.CharField(max_length=5, null=True)),
                ('vvp_kt', models.CharField(max_length=5, null=True)),
                ('bd', models.CharField(max_length=5, null=True)),
                ('bg', models.CharField(max_length=5, null=True)),
                ('ktc', models.CharField(max_length=5, null=True)),
                ('sonde_gast', models.CharField(max_length=5, null=True)),
                ('sonde_vest', models.CharField(max_length=5, null=True)),
                ('collier_cervical', models.CharField(max_length=5, null=True)),
                ('attelles', models.CharField(max_length=5, null=True)),
                ('drain_pleural', models.CharField(max_length=5, null=True)),
                ('autre', models.CharField(max_length=255, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'mise_en_condition',
            },
        ),
    ]
