# Generated by Django 3.0.5 on 2024-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0013_mise_en_condition_solutes_drogues_voies_aeriennes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mise_en_condition',
            name='attelles',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mise_en_condition',
            name='barquette',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mise_en_condition',
            name='bd',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mise_en_condition',
            name='bg',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mise_en_condition',
            name='collier_cervical',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mise_en_condition',
            name='coquille',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mise_en_condition',
            name='drain_pleural',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mise_en_condition',
            name='dyn',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mise_en_condition',
            name='ktc',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mise_en_condition',
            name='oxy',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mise_en_condition',
            name='scope',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mise_en_condition',
            name='sonde_gast',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mise_en_condition',
            name='sonde_vest',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mise_en_condition',
            name='vvp_kt',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
