# Generated by Django 3.0.5 on 2024-04-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0014_auto_20240422_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='voies_aeriennes',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient'),
        ),
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.CharField(max_length=25)),
                ('poul', models.CharField(max_length=25)),
                ('TA', models.CharField(max_length=25)),
                ('FR', models.CharField(max_length=25)),
                ('spo2_fioo2', models.CharField(max_length=25)),
                ('temperature', models.CharField(max_length=25)),
                ('glasgow', models.CharField(max_length=25)),
                ('glycemie', models.CharField(max_length=25)),
                ('douleur', models.CharField(max_length=25)),
                ('diurese', models.CharField(max_length=25)),
                ('commentaire', models.CharField(max_length=155)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_register.Patient')),
            ],
            options={
                'db_table': 'constant',
            },
        ),
    ]
