# Generated by Django 3.0.5 on 2024-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0015_auto_20240424_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Consommables',
            },
        ),
    ]
